version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Only when we hosted the API to VPS
    # restart: always
    container_name: backend-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
