// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	Username    string  `json:"username"`
	Image       *string `json:"image,omitempty"`
	Description *string `json:"description,omitempty"`
}

type Blog struct {
	ID        string    `json:"id"`
	Slug      string    `json:"slug"`
	Thumbnail *string   `json:"thumbnail,omitempty"`
	Author    *string   `json:"author,omitempty"`
	Title     *string   `json:"title,omitempty"`
	CreatedAt *string   `json:"createdAt,omitempty"`
	UpdatedAt *string   `json:"updatedAt,omitempty"`
	DeletedAt *string   `json:"deletedAt,omitempty"`
	Content   string    `json:"content"`
	Tags      []*string `json:"tags"`
}

type Query struct {
}
